// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odfuxjsxdcmugekpmrez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZnV4anN4ZGNtdWdla3BtcmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTM4NjIsImV4cCI6MjA2NTA2OTg2Mn0.4A1ESQZjiVyO30ApJwV6PUeMkTNhsxZjOJhQbJapZlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);